descriptor-schema-version: 2.5
 
info:
  name: TestMotionApp 
  description: "Get gyroscope and accelerometer data from service"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"
 
app:
  cpuarch: "x86_64"
  type: docker

  depends-on:
    packages:
      -
        name: "IOxCore"
        version: "1.4.0"
      -
        name: "Gyroscope"
        version: "1.4.0"

  resources:
    profile: custom
    cpu: "50"
    disk: "10"
    memory: "64"
    oauth: [OauthClient]

    network:
     -
       interface-name: eth0


  # Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["/usr/share/motionapp/motion.sh start"]

