#%RAML 0.8

title: Average Temperature Service
iox.service: urn:cisco:system:service:average-temperature
baseUri: /api/v1/mw
securitySchemes: !include security.raml
securedBy: [basic, token]
version: v1
/getAvgTemperature:
  get:
    description: get average temperature data
    iox.operation:
      name: getAvgTemperature
    responses:
      200:
        body:
          application/json:
          text/json:
