descriptor-schema-version: "2.5"

info:
  name: GPS application
  description: Sample Application that makes use of GPS Protocol Handler
  version: "0.9.4"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: "x86_64"
  type: docker

  depends-on:
    packages:
      -
        name: "IOxCore"
        version: "1.4.0"
      -
        name: "IOxGPS"
        version: "1.4.0"

  resources:
    profile: custom
    cpu: "100"
    disk: "20"
    memory: "50"
    oauth: [OauthClient]

    network:
     -
       interface-name: eth0

  # Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["/usr/share/gpsapp/gpsapp.sh start"]
